[package]
name = "electrs"
version = "0.4.1"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"

[features]
default = [ "rocksdb" ]
liquid = [ "elements" ]
oldcpu = [ "rocksdb-oldcpu" ]

[dependencies]
arraydeque = "0.4"
arrayref = "0.3.6"
base64 = "0.12.0"
bincode = "1.2.1"
chan = "0.1"
chan-signal = "0.3"
clap = "2.31"
dirs = "2.0"
error-chain = "0.12.2"
futures = "0.1"
glob = "0.3"
hex = "0.4.2"
hyper = "0.12.33"
itertools = "0.9.0"
lazy_static = "1.3.0"
libc = "0.2.68"
log = "0.4"
lru = "0.3"
lru-cache = "0.1.1"
monacoin = { git = "https://github.com/wakiyamap/rust-monacoin/", rev = "670d749a02b6f711ce09ac57b1d065dbd73e014b", features = ["use-serde"] }
num_cpus = "1.12.0"
page_size = "0.4.2"
prometheus = "0.7"
rayon = "1.3.0"
rocksdb = { version = "0.13.0", optional = true }
rocksdb-oldcpu = { version = "0.12.4", optional = true, package = "rocksdb" }
rust-crypto = "0.2"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
stderrlog = "0.4.3"
sysconf = ">=0.3.4"
time = "0.1"
tiny_http = "0.6"
url = "2.1.1"

[dependencies.bitcoin]
version = "0.23.0"
features = ["use-serde"]

[dependencies.elements]
optional = true
version = "0.12.1"
features = ["serde-feature"]

[dev-dependencies]
tempfile = "3.1"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[patch.crates-io.bitcoin]
git = "https://github.com/blockstream/rust-bitcoin"
rev = "0.23-electrs"

[patch.crates-io.elements]
git = "https://github.com/elementsproject/rust-elements"
rev = "fc27e53046d531b5ea65617fbfeea62e84ba10d4"
